name: "🛠 Improvement"
description: Suggest improvements or enhancements to existing functionality.
type: "Improvement"
labels:
  - "status: needs triage"
projects:
    - "SLNE-Development/3"

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an improvement! Please provide detailed information so we can evaluate and address your suggestion.
  - type: textarea
    attributes:
      label: What Needs Improvement?
      description: Describe the issue or aspect of the project that you believe could be improved.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed Improvement
      description: Provide a detailed explanation of your suggested improvement.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Benefits of the Improvement
      description: Explain how this improvement would benefit the project or its users.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: Include any additional context, screenshots, or links that may help in understanding your suggestion.
    validations:
      required: false
