name: "🐛 Bug or Incompatibility"
description: Report issues related to unexpected behavior or vanilla/plugin incompatibility.
type: "Bug"
projects:
    - "CastCrafter/3"
labels:
    - "status: needs triage"

body:
    - type: markdown
      attributes:
          value: |
              Before submitting this issue, please ensure the following:

              1. You have searched to confirm there isnt an existing open issue on this topic.

    - type: textarea
      attributes:
          label: Expected behavior
          description: What you expected to see.
      validations:
          required: true

    - type: textarea
      attributes:
          label: Observed/Actual behavior
          description: What you actually saw.
      validations:
          required: true

    - type: textarea
      attributes:
          label: Steps/models to reproduce
          description: This may include a build schematic, a video, or detailed instructions to help reconstruct the issue.
      validations:
          required: true

    - type: textarea
      attributes:
          label: Other
          description: |
              Please include other helpful information below.
              The more information we receive, the quicker and more effective we can be at finding the solution to the issue.
      validations:
          required: false
